// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVBpixJ5S3JlS2Zd3_gyywmkKVE7ymgoU',
    appId: '1:538816770292:web:5e52be2a612b95f1076ea1',
    messagingSenderId: '538816770292',
    projectId: 'reddit-clone-flutter',
    authDomain: 'reddit-clone-flutter.firebaseapp.com',
    storageBucket: 'reddit-clone-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYofk57HfFtoMUnVOuq9m-ABkJxCo_DVM',
    appId: '1:538816770292:android:562995fc0b950f2c076ea1',
    messagingSenderId: '538816770292',
    projectId: 'reddit-clone-flutter',
    storageBucket: 'reddit-clone-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzsKOWg3RC1-BtX1vK5_VDg6IlSmioAa8',
    appId: '1:538816770292:ios:281e947c85436741076ea1',
    messagingSenderId: '538816770292',
    projectId: 'reddit-clone-flutter',
    storageBucket: 'reddit-clone-flutter.appspot.com',
    iosClientId: '538816770292-49b08agmo4vco26oebajf24emhq7h5d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
